#!/usr/bin/env bash
# Rebuilds everything derived from assets/demo-photos/*.jpg:
#
#   integration_test/demo_photos.g.dart   the fixture the screenshot driver
#                                         uploads, so the photos inside the app
#                                         screenshots are these photos
#   apps/website/public/photos/           web-sized copies for the site
#
# The screenshot test runs on the simulator and cannot read files from this
# machine, so its copies travel as base64 inside a generated Dart file. That is
# also why they are downscaled hard first: the fixture is committed.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

SRC=assets/demo-photos
WEB=apps/website/public/photos
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

shopt -s nullglob
PHOTOS=("$SRC"/*.jpg)
[ ${#PHOTOS[@]} -gt 0 ] || { echo "no photos in $SRC" >&2; exit 1; }

mkdir -p "$WEB"
rm -f "$WEB"/*.jpg

for p in "${PHOTOS[@]}"; do
  n=$(basename "$p" .jpg)
  # 600px tall at quality 55: the app only ever shows these inside a phone-sized
  # frame, and every byte here is committed twice over (jpeg + base64).
  sips -s format jpeg -s formatOptions 55 -Z 600 "$p" --out "$TMP/$n.jpg" >/dev/null
  # The site shows them larger — in a marquee and full-bleed — so they get more.
  sips -s format jpeg -s formatOptions 72 -Z 1000 "$p" --out "$WEB/$n.jpg" >/dev/null
done

python3 - "$TMP" <<'PY'
import base64, pathlib, sys

tmp = pathlib.Path(sys.argv[1])
parts = []
for f in sorted(tmp.glob("*.jpg")):
    b = base64.b64encode(f.read_bytes()).decode()
    lit = "\n      ".join(f"'{b[i:i+100]}'" for i in range(0, len(b), 100))
    parts.append(f"  // {f.name}\n  {lit},")

pathlib.Path("integration_test/demo_photos.g.dart").write_text(
    "// GENERATED by scripts/generate-demo-photos.sh — do not edit.\n"
    "//\n"
    "// The camera roll the marketing-screenshot run plays with. Real\n"
    "// photographs, from Unsplash under a licence that permits it — see\n"
    "// assets/demo-photos/README.md for the photographers. A game about\n"
    "// people's camera rolls has to be photographed with photographs.\n\n"
    "const List<String> demoPhotosBase64 = <String>[\n" + "\n".join(parts) + "\n];\n")
print(f"wrote integration_test/demo_photos.g.dart ({len(parts)} photos)")
PY

echo "wrote $WEB ($(ls -1 "$WEB" | wc -l | tr -d ' ') photos, $(du -sh "$WEB" | cut -f1))"
