#!/usr/bin/env bash
# Rebuilds integration_test/demo_photos.g.dart from assets/demo-photos/*.svg.
#
# The screenshot test runs on the simulator, so it cannot read image files from
# this machine; the photos travel as base64 inside a generated Dart file.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

NAMES=(sunset mountains city beach table forest)
for n in "${NAMES[@]}"; do
  # 600x800 keeps the generated Dart file reasonable; these are only ever shown
  # inside a phone-sized frame.
  swift scripts/rasterize-svg.swift "assets/demo-photos/$n.svg" opaque "$TMP/$n.png:600x800"
done

python3 - "$TMP" "${NAMES[@]}" <<'PY'
import base64, pathlib, sys
tmp, names = pathlib.Path(sys.argv[1]), sys.argv[2:]
parts = []
for n in names:
    b = base64.b64encode((tmp / f"{n}.png").read_bytes()).decode()
    lit = "\n      ".join(f"'{b[i:i+100]}'" for i in range(0, len(b), 100))
    parts.append(f"  // {n}.png\n  {lit},")
pathlib.Path("integration_test/demo_photos.g.dart").write_text(
    "// GENERATED by scripts/generate-demo-photos.sh — do not edit.\n"
    "//\n"
    "// Illustrative photos used by the marketing-screenshot run. They are drawn\n"
    "// rather than real: a screenshot of a game about people's private photos\n"
    "// should not contain anybody's private photos.\n\n"
    "const List<String> demoPhotosBase64 = <String>[\n" + "\n".join(parts) + "\n];\n")
print("wrote integration_test/demo_photos.g.dart")
PY
